#!/bin/bash
# =================[TorMux]===================
# Versión: 2.0
# Open Source - Software Libre
# O.S: Kali Linux - Parrot OS - Termux
# License: General Public License
# Coded by: Ux4hack
#
# ##############################################
# NOTA: Si copias código recuerda darme créditos
# ##############################################
#
# Colores
R='\033[1;31m'
G='\033[1;32m'
Y='\033[1;33m'
B='\033[1;34m'
M='\033[1;35m'
C='\033[1;36m'
W='\033[0m'
GR='\e[90m'
LRED="\e[101m"
DGRAY="\e[100m"

# Función para mostrar el banner
function banner {
    clear
    echo -e "${GR}           ${W}-[${GR}Ux4hack${W}]- ${GR}
         ████████╗ █████╗ ██████╗
         ╚══██╔══╝██╔══██╗██╔══██╗
            ██║   ██║  ██║██████╔╝
            ██║   ██║  ██║██╔══██╗
            ██║   ╚█████╔╝██║  ██║
${R}            ╚═╝    ╚════╝ ╚═╝  ╚═╝${W} [${GR}Mux${W}]"
    echo -e "          ${W}${LRED}::The Onion Router::${W}"
    echo -e "    ${W}${DGRAY}.:Anonimíza tus procesos hacking:.${W}"
    echo
}

# Función para instalar dependencias
function install_deps {
    echo -e "${R}      ╭─────────────────────────╮
      │ ${W}Instalando dependencias${R} │
      ╰─────────────────────────╯${W}"
    sleep 1
}

# Mostrar el banner
banner

echo -e "${R}╭───────────────────────────────╮
│ ${W}Presiona${R} ENTER ${W}Para continuar${R} │
╰───────────────────────────────╯${W}"
read enter

# Detectar el gestor de paquetes según el sistema operativo
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    if [[ -f "/etc/os-release" ]]; then
        source "/etc/os-release"
        if [[ "$NAME" == "Kali GNU/Linux" || "$NAME" == "Parrot" ]]; then
            package_manager="apt-get"
        else
            echo "No se pudo detectar el gestor de paquetes compatible para tu distro de Linux."
            exit 1
        fi
    else
        echo "No se pudo detectar la distribución de Linux."
        exit 1
    fi
elif [[ "$(uname -o)" == "Android" ]]; then
    package_manager="pkg"
else
    echo "Sistema operativo no compatible."
    exit 1
fi

# Mostrar el banner y instalar dependencias
banner
install_deps

echo -e "${R}╭────────────────╮
│ ${W}Instalando tor${R} │
╰────────────────╯${W}"
sleep 1
yes | $package_manager install tor

# Mostrar el banner y instalar dependencias
banner
install_deps

echo -e "${R}╭────────────────╮
│ ${W}Instalando w3m${R} │
╰────────────────╯${W}"
sleep 1
yes | $package_manager install w3m

# Mostrar el banner y instalar dependencias
banner
install_deps

echo -e "${R}╭─────────────────────╮
│ ${W}Instalando torsocks${R} │
╰─────────────────────╯${W}"
sleep 1
yes | $package_manager install torsocks

# Mostrar el banner y instalar dependencias
banner
install_deps

echo -e "${R}╭───────────────────────────╮
│ ${W}Instalando proxychains-ng${R} │
╰───────────────────────────╯${W}"
sleep 1

# Copiar archivos y establecer permisos
banner
if [[ "$(uname -o)" == "Android" ]]; then
    cp -r tor-help $PREFIX/bin
    chmod 777 $PREFIX/bin/tor-help
    cp -r infomyip $PREFIX/bin
    chmod 777 $PREFIX/bin/infomyip
    cp -r iptor $PREFIX/bin
    chmod 777 $PREFIX/bin/iptor
    cp -r pubip $PREFIX/bin
    chmod 777 $PREFIX/bin/pubip
    cp -r infoip $PREFIX/bin
    chmod 777 $PREFIX/bin/infoip
    cp -r ipch $PREFIX/bin
    chmod 777 $PREFIX/bin/ipch
    cp -r privip $PREFIX/bin
    sleep 1

    echo -e "${R}       ╭─────────────────────────╮
       │ ${W}Dependencias instaladas ${R}│
       ╰─────────────────────────╯${W}"
    echo
    echo -e "${GR} [${R}*${GR}]${W} Github: ${GR}Ux4hack"
    echo -e "${GR} [${R}*${GR}]${W} Telegram: ${GR}@Ux4hack"
    echo
    exit 1
else
    sudo cp -r tor-help /usr/bin
    sudo chmod 777 /usr/bin/tor-help
    sudo cp -r infomyip /usr/bin
    sudo chmod 777 /usr/bin/infomyip
    sudo cp -r iptor /usr/bin
    sudo chmod 777 /usr/bin/iptor
    sudo cp -r pubip /usr/bin
    sudo chmod 777 /usr/bin/pubip
    sudo cp -r infoip /usr/bin
    sudo chmod 777 /usr/bin/infoip
    sudo cp -r ipch /usr/bin
    sudo chmod 777 /usr/bin/ipch
    sudo cp -r privip /usr/bin
    sleep 1

    echo -e "${R}       ╭─────────────────────────╮
       │ ${W}Dependencias instaladas ${R}│
       ╰─────────────────────────╯${W}"
    echo
    echo -e "${GR} [${R}*${GR}]${W} Github: ${GR}Ux4hack"
    echo -e "${GR} [${R}*${GR}]${W} Telegram: ${GR}@Ux4hack"
    echo
    exit 1
fi

# I'm Ux4hack
